language: ruby
script: "bundle exec rake spec"
notifications:
  email:
    recipients:
      - softwaredev-notify@wwwh.com
    on_success: never
    on_failure: always
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
  - jruby-19mode
